1. Demostrar que los valores singulares de $\mathbf{A}^{-1}$, son $1 / \sigma_{1}, 1 / \sigma_{2}, \ldots, 1 / \sigma_{n}$, si los $\sigma$ 's son los valores singulares de $\mathbf{A}$.

  Sabemos por propiedades de los valores propios que: $\alpha \mathbf{A}=\alpha \mathbf{b}$
  
  Elevamos toda la ecuación a la -1: $(\alpha \mathbf{A}=\alpha \mathbf{b})^{-1}$
  
  Por propiedades distributivas de la inversa: $({\alpha}) \mathbf{A}^{-1}=(1 / \alpha) \mathbf{b}^{-1}$ para $\alpha<>0$
  

  Hagamos el siguiente ejemplo:
  
\begin{equation}
\boldsymbol{A}=\left[\begin{array}{lll}
1 & 7  \\
4 & 3  \\
\end{array}\right]
\end{equation}



In [1]:
import numpy as np

In [4]:
A=np.array([[1,7],[4,3]])
iA=np.linalg.inv(A)
print(A,'\n','\n',iA,'\n','\n')

eA, evA=np.linalg.eig(A)
eiA, eviA=np.linalg.eig(iA)
print("Valores propios de A: ",eA,'\n',"Valores propios de A inversa: ",eiA,'\n','\n')
print("valores propios de A: ",eA," valores propios A inversa calculado 1/valores de A: ",1/eA)

[[1 7]
 [4 3]] 
 
 [[-0.12  0.28]
 [ 0.16 -0.04]] 
 

Valores propios de A:  [-3.38516481  7.38516481] 
 Valores propios de A inversa:  [-0.29540659  0.13540659] 
 

valores propios de A:  [-3.38516481  7.38516481]  valores propios A inversa calculado 1/valores de A:  [-0.29540659  0.13540659]


2. Demostrar que
$$
\left|\mathbf{A}^{-1}\right|=\frac{1}{|\mathbf{A}|}
$$
Usando la descomposicion en valores singulares.
$$
\operatorname{Det}(\mathrm{A})=\alpha_{1}^{*} \alpha_{2}{ }^{*} \ldots * \alpha_{\mathrm{n}}
$$
Del ejercicio anterior: $\left(1 /{{\alpha}) \mathbf{A}^{-1}}=(1 / \alpha) \mathbf{c}\right.$
$$
\begin{aligned}
&\operatorname{Det}\left(A^{-1}\right)=\left(1 / \alpha_{1}\right)^{*}\left(1 / \alpha_{2}\right)^{*} \ldots^{*}\left(1 / \alpha_{n}\right) \\
&\operatorname{Det}\left(A^{-1}\right)=1 /\left(\alpha_{1} * \alpha_{2}^{*} \ldots^{*} \alpha_{n}\right) \\
&\operatorname{Det}\left(A^{-1}\right)=1 / \operatorname{Det}(A)
\end{aligned}
$$

  Hagamos el siguiente ejemplo:
  
\begin{equation}
\boldsymbol{A}=\left[\begin{array}{lll}
1 & 7  \\
4 & 3  \\
\end{array}\right]
\end{equation}

In [ ]:
A=np.array([[1,7],[4,3]])
iA=np.linalg.inv(A)
print(A,'\n','\n',iA,'\n','\n')
print("determinante de A: ",np.linalg.det(A)," determinante de A inversa: ",np.linalg.det(iA)," 1/determinante A: ",1/(np.linalg.det(A)))

[[1 7]
 [4 3]] 
 
 [[-0.12  0.28]
 [ 0.16 -0.04]] 
 

determinante de A:  -25.000000000000007  determinante de A inversa:  -0.03999999999999999  1/determinante A:  -0.03999999999999999


3.1. Se tiene una matriz de la forma
$$
\mathbf{A}=\left[\begin{array}{cc}
\mathbf{A}_{11} & \mathbf{A}_{12} \\
\mathbf{0} & \mathbf{A}_{22}
\end{array}\right]
$$

Asuma que $\mathbf{A}_{11}$ es $p \times p, \mathbf{A}_{22}$ es $q \times q, \mathrm{y}$ A es invertible. Demostrar que

$$
\mathbf{A}^{-1}=\left[\begin{array}{cc}
\mathbf{A}_{11}^{-1} & -\mathbf{A}_{11}^{-1} \mathbf{A}_{12} \mathbf{A}_{22}^{-1} \\
\mathbf{0} & \mathbf{A}_{22}^{-1}
\end{array}\right]
$$

\begin{aligned}
&\boldsymbol{A}=\left[\begin{array}{cc}
A 11 & A 12 \\
0 & A 22
\end{array}\right] \\
&{\left[\begin{array}{cc}
1 & -A 12 & A 22^{-1} \\
0 & 1
\end{array}\right]\left[\begin{array}{cc}
A 11 & A 12 \\
0 & A 22
\end{array}\right]} \\
&{\left[\begin{array}{cc}
A 11^{-1} & 0 \\
0 & A 22^{-1}
\end{array}\right]\left[\begin{array}{cc}
A 11 & 0 \\
0 & A 22
\end{array}\right]=\left[\begin{array}{cc}
1 & 0 \\
0 & 1
\end{array}\right]} \\
&A^{-1}=\left[\begin{array}{cc}
A 11^{-1} & 0 \\
0 & A 22^{-1}
\end{array}\right]\left[\begin{array}{cc}
1 & -A 12 A 22^{-1} \\
0 & 1
\end{array}\right]= \\
&{\left[\begin{array}{cc}
A 11^{-1} & -A 11^{-1} A 12 A 22^{-1} \\
0 & A 22^{-1}
\end{array}\right]}
\end{aligned}

2.3. Realizar el problema $1.3$ en el PC. Generar las matrices $\mathbf{A}_{11}, \mathbf{A}_{12}$ y $\mathbf{A}_{22}$ de manera aleatoria, para $p=3$ y $q=5$. Verificar que se cumple la demonstración.


Para poder realizar la demostración, la matriz A debe ser 3x5, es decir qxp para poder realizar las operaciones entre matrices


Para verificar el valor, al hacer la multiplicación de A y A inversa debería darnos:

En la posición A11 y A22 la matriz identidad y en la posición A12 y A21 una matriz de ceros.

\begin{equation}
\left[A A^{-1}\right]=I
\end{equation}

\begin{equation}
\left[\begin{array}{cc}
A 11 & A 12 \\
0 & A 22
\end{array}\right]\left[\begin{array}{cc}
A 11^{-1} & -A 11^{-1} A 12 A 22^{-1} \\
0 & A 22^{-1}
\end{array}\right]=
\end{equation}
\begin{equation}
\left[\begin{array}{cc}
A 11 A 11^{-1}+A 12 * 0 & A 11\left(-A 11^{-1} A 12 A 22^{-1}\right)+A 12 A 22^{-1} \\
0 * A 11^{-1}+A 22 * 0 & 0 *-A 11^{-1} A 12 A 22^{-1}+A 22 A 22^{-1}
\end{array}\right]
\end{equation}

\begin{equation}
\left[\begin{array}{cc}
A 11 A 11^{-1} & A 11\left(-A 11^{-1} A 12 A 22^{-1}\right)+A 12 A 22^{-1} \\
0 & A 22 A 22^{-1}
\end{array}\right]=I
\end{equation}

In [ ]:
A11=np.random.randn(3,3)
A22=np.random.randn(5,5)
A12=np.random.rand(3,5)
A=np.array([[A11,A12],[0,A22]])

A11inv=np.linalg.inv(A11)
A22inv=np.linalg.inv(A22)
A12f=-A11inv@A12@A22inv

AF=np.array([[A11inv,A12f],[0,A22inv]])

print("A es: ",'\n',A,'\n \n')
print("A inversa es: ",'\n',AF,'\n \n')

print("La matriz A11 es: ",'\n \n',A11inv@A11,'\n')
print("La matriz A12 es: ",'\n \n',A11inv@A12+A12f@A22,'\n') #debe dar casi cero
print("La matriz A21 es: ",'\n \n', 0)
print("La matriz A22 es: ",'\n \n',A22@A22inv)



A es:  
 [[array([[-0.5862438 ,  0.95879582, -1.07593976],
       [-0.54009456,  0.44191568, -1.3159585 ],
       [-1.36098681, -0.02954976, -0.65873143]])
  array([[0.32318802, 0.7562679 , 0.42000174, 0.8674665 , 0.0010754 ],
       [0.7260369 , 0.57615621, 0.94112124, 0.57581169, 0.60336473],
       [0.92313335, 0.05552567, 0.69542674, 0.98078284, 0.7257496 ]])]
 [0
  array([[ 0.77166116, -1.90998055, -0.28295529, -0.30579593,  1.44669917],
       [-1.65569619, -0.69099352,  1.9914331 , -0.74365958, -0.25450564],
       [-0.83189447, -0.35427055,  0.80753611, -1.11330137, -0.85985564],
       [-0.41931615, -0.45171539, -0.4525053 ,  0.08590075,  0.43262107],
       [ 0.88336109,  1.13052707,  0.03061836,  0.20536547, -2.89399707]])]] 
 

A inversa es:  
 [[array([[-0.36452678,  0.73281237, -0.86855097],
       [ 1.58543563, -1.19100317, -0.21028674],
       [ 0.68201831, -1.46061669,  0.28585297]])
  array([[ 0.2084736 ,  0.48981994, -0.987066  ,  0.13566822,  0.30952846],
       [ 0

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  after removing the cwd from sys.path.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:10: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  # Remove the CWD from sys.path while we load stuff.


2.1. Encuentre la solución de mínimos cuadrados al problema $\mathbf{A x}=\mathbf{b}$ usando la factorización $\mathrm{QR}$, y resolviendo por medio de $\mathbf{R x}=\mathbf{Q}^{\top} \mathbf{b} .$ Donde $\mathbf{R x}$ se resuelve por sustitución hacia atrás.

$$
\mathbf{A}=\left[\begin{array}{ccc}
4 & 0 & 1 \\
1 & -5 & 1 \\
6 & 1 & 0 \\
1 & -1 & -5
\end{array}\right], \quad \mathbf{b}=\left[\begin{array}{l}
9 \\
0 \\
0 \\
0
\end{array}\right]
$$

IRx=Qt

In [ ]:
A=np.array([[4,0,1],[1,-5,1],[6,1,0],[1,-1,-5]])
b=np.array([[9],[0],[0],[0]])

#Encontrar los vectores ortonormales por chismosear y chicanear
q1=A[:,0]
q1=q1/np.linalg.norm(q1)

a2=A[:,1]
q2=a2-np.dot(q1,a2)*q1
q2=q2/np.linalg.norm(q2)

a3=A[:,2]
q3=a3-np.dot(q2,a3)*q2-np.dot(q2,a3)*q2
q3=q3/np.linalg.norm(q3)

print("Los vectores q: ",'\n',q1)
print(q2)
print(q3,'\n')

print("Verificamos ortogonalidad: ",'\n',np.dot(q1,q2))
print(np.dot(q1,q3))
print(np.dot(q2,q3),'\n')

q=np.concatenate(([q1],[q2],[q3]),axis=0)
print("matriz q: ",'\n',q)

Los vectores q:  
 [0.54433105 0.13608276 0.81649658 0.13608276]
[ 0.         -0.96225045  0.19245009 -0.19245009]
[ 1.92450090e-01  1.92450090e-01 -4.11193713e-18 -9.62250449e-01] 

Verificamos ortogonalidad:  
 1.9109342704268683e-17
-1.1390925029178527e-17
1.374877180409105e-17 

matriz q:  
 [[ 5.44331054e-01  1.36082763e-01  8.16496581e-01  1.36082763e-01]
 [ 0.00000000e+00 -9.62250449e-01  1.92450090e-01 -1.92450090e-01]
 [ 1.92450090e-01  1.92450090e-01 -4.11193713e-18 -9.62250449e-01]]


A@x = b

R@x = Q.T@b

A = Q@R

\begin{equation}
\hat{\mathbf{x}}=\left(\mathbf{A}^{\top} \mathbf{A}\right)^{-1} \mathbf{A}^{\top} \mathbf{b}=\mathbf{A}^{\dagger} \mathbf{b}=\mathbf{R}^{-1} \mathbf{Q}^{\top} \mathbf{b}
\end{equation}


Hallamos Rx con backward sustitution

In [ ]:
Q,R=np.linalg.qr(A)
xc1=np.linalg.solve(R,(Q.T@b))

print(xc1)

[[ 6.66666667e-01]
 [-4.42432214e-17]
 [ 3.33333333e-01]]


2.2. Realizar el problema anterior usando $\hat{\mathbf{x}}=\left(\mathbf{A}^{\top} \mathbf{A}\right)^{-1} \mathbf{A}^{\top} \mathbf{b}$. Comparar si la matriz $\left(\mathbf{A}^{\top} \mathbf{A}\right)^{-1} \mathbf{A}^{\top}$ corresponde a la pseudo inversa, típicamente denotada como pinv en las librerías de algebra lineal.

In [ ]:
A=np.array([[4,0,1],[1,-5,1],[6,1,0],[1,-1,-5]])
b=np.array([[9],[0],[0],[0]])

Q,R = np.linalg.qr(A)
print(Q,'\n \n',R)
x=np.linalg.solve(A.T@A,(A.T@b))

Ai1=np.linalg.inv((A.T@A))@A.T
Ai2=np.linalg.pinv(A)

print('\n \n',"Con la aplicación QR, los valores de x son ",'\n',x)
print('\n',"(AT A)^-1 AT: ",'\n',Ai1,'\n \n',"la pseudoinversa: ",'\n',Ai2)


[[-5.44331054e-01 -2.14318987e-17  1.92450090e-01]
 [-1.36082763e-01 -9.62250449e-01  1.92450090e-01]
 [-8.16496581e-01  1.92450090e-01  1.33437137e-17]
 [-1.36082763e-01 -1.92450090e-01 -9.62250449e-01]] 
 
 [[-7.34846923e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  5.19615242e+00  1.11022302e-16]
 [ 0.00000000e+00  0.00000000e+00  5.19615242e+00]]

 
 Con la aplicación QR, los valores de x son  
 [[0.66666667]
 [0.        ]
 [0.33333333]]

 (AT A)^-1 AT:  
 [[ 0.07407407  0.01851852  0.11111111  0.01851852]
 [ 0.         -0.18518519  0.03703704 -0.03703704]
 [ 0.03703704  0.03703704  0.         -0.18518519]] 
 
 la pseudoinversaa:  
 [[ 7.40740741e-02  1.85185185e-02  1.11111111e-01  1.85185185e-02]
 [-4.12457082e-18 -1.85185185e-01  3.70370370e-02 -3.70370370e-02]
 [ 3.70370370e-02  3.70370370e-02  2.56799889e-18 -1.85185185e-01]]


Hay que tener en cuenta que esta factorización nos genera un márgen de error, ya que el resultado se encuentra en los R^n, busca el resultado más apróximado en el plano que forma nuestra matriz, pero si no está conferido, nos genera grandes errores. 

Finalmente, se verificó el resultado de la ecuación por ambos metodos, desde la pseudoinversa y Rx

\begin{equation}
\hat{\mathbf{x}}=\left(\mathbf{A}^{\top} \mathbf{A}\right)^{-1} \mathbf{A}^{\top} \mathbf{b}=\mathbf{A}^{\dagger} \mathbf{b}=\mathbf{R}^{-1} \mathbf{Q}^{\top} \mathbf{b}
\end{equation}

2.4. La matriz de banda A mostrada abajo puede ser utilizada para estimar la conducción inestable de calor en una barra cuando la temperatura en los puntos $p_{1}, \ldots, p_{5}$ sobre la barra cambian con el tiempo.

La constante $C$ en una matriz depende de la naturaleza física de la barra, la distancia $\Delta x$ entre los puntos sobre la barra, $y$ la longitud del tiempo $\Delta t$ entre medidas sucesivas de temperaturas. Suponga que para $k=0,1,2, \ldots$ un vector $\mathbf{t}_{k} \in \mathbb{R}^{5}$ contiene las temperaturas

en el tiempo $k \Delta t .$ Si los dos finales de la barra se mantienen en $0^{\circ}$, entonces los vectores temperatura satisfacen la ecuación $\mathbf{A t}_{k+1}=\mathbf{t}_{k}($ con $k=0,1, \ldots)$, donde
$$
\mathbf{A}=\left[\begin{array}{ccccc}
(1+2 C) & -C & & & \\
-C & (1+2 C) & -C & & \\
& -C & (1+2 C) & -C & \\
& & -C & (1+2 C) & -C \\
& & & -C & (1+2 C)
\end{array}\right]
$$
(a) Determine la factorización $\mathrm{LU}$ de $\mathbf{A}$ cuando $C=1 .$ Una matriz como A con tres diagonales diferentes de cero es llamada matriz tri-diagonal. Los factores $\mathbf{L} \mathrm{y} \mathbf{U}$ son matrices bi-diagonales.

(b) Suponga que $C=1$ y $\mathbf{t}_{0}=[10,12,12,12,10]^{\top} .$ Usar la factorización $\mathrm{LU}$ de $\mathbf{A}$ para encontrar la distribución de temperaturas $\mathbf{t}_{1}, \mathbf{t}_{2}, \mathbf{t}_{3}, \mathrm{y} \mathbf{t}_{4}$


In [ ]:
from scipy.linalg import lu
A=np.array([[3,-1,0,0,0],[-1,3,-1,0,0],[0,-1,3,-1,0],[0,0,-1,3,-1],[0,0,0,-1,3]])
P,L,U=lu(A)
print(P,'\n')
print("Matriz bidiagonal inferior L: ",'\n',L,'\n')
print("Matriz bidiagonal superior U: ",'\n',U,'\n')
print("Matriz tridiagonal A: ",'\n',P@(L@U))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]] 

Matriz bidiagonal inferior L:  
 [[ 1.          0.          0.          0.          0.        ]
 [-0.33333333  1.          0.          0.          0.        ]
 [ 0.         -0.375       1.          0.          0.        ]
 [ 0.          0.         -0.38095238  1.          0.        ]
 [ 0.          0.          0.         -0.38181818  1.        ]] 

Matriz bidiagonal superior U:  
 [[ 3.         -1.          0.          0.          0.        ]
 [ 0.          2.66666667 -1.          0.          0.        ]
 [ 0.          0.          2.625      -1.          0.        ]
 [ 0.          0.          0.          2.61904762 -1.        ]
 [ 0.          0.          0.          0.          2.61818182]] 

Matriz tridiagonal A:  
 [[ 3. -1.  0.  0.  0.]
 [-1.  3. -1.  0.  0.]
 [ 0. -1.  3. -1.  0.]
 [ 0.  0. -1.  3. -1.]
 [ 0.  0.  0. -1.  3.]]


**PA=LU** Entonces:
**LUx=Pb, PAx=Pb**

Para el calculo de las temperaturas hay que calcular las anteriores, primero t1

In [ ]:
t=np.array([[10],[12],[12],[12],[10]])
t1=np.linalg.solve(U,np.linalg.solve(L,P@t))
print("t1= ",'\n',t1)

t1=  
 [[ 6.55555556]
 [ 9.66666667]
 [10.44444444]
 [ 9.66666667]
 [ 6.55555556]]


In [ ]:
t2=np.linalg.solve(U,np.linalg.solve(L,P@t1))
t3=np.linalg.solve(U,np.linalg.solve(L,P@t2))
t4=np.linalg.solve(U,np.linalg.solve(L,P@t3))
print("t2= ",'\n',t2)
print("t3= ",'\n',t3)
print("t4= ",'\n',t4)

t2=  
 [[4.74074074]
 [7.66666667]
 [8.59259259]
 [7.66666667]
 [4.74074074]]
t3=  
 [[3.59876543]
 [6.05555556]
 [6.90123457]
 [6.05555556]
 [3.59876543]]
t4=  
 [[2.79218107]
 [4.77777778]
 [5.48559671]
 [4.77777778]
 [2.79218107]]
